
<section class="caixa1">
	<div class="row">
		<div class="col-5">
			<div class="caixa-interior">
				<ul class="ul">
					<li class="li"><i class="fa-brands fa-facebook-f"></i>
					Facebook</li>
					<li class="li"><i class="fa-brands fa-instagram"></i></i>
					Instagram</li>
					<li class="li"><i class="fa-brands fa-twitter"></i></i>
					Twitter</li>
					

				</ul>
				<p>
					Caso não tenha cadastro, <a href="">clique aqui</a>
				</p>
				<hr>
				</div>
		</div>
		<div class="col">
			<div class="caixa2">
				<div class="caixa-login">
					<form class="caixa-login-interior" action="/autenticar" method="post">
						<input type="email" name="email" class="form-control mt-3" placeholder="Email"> 

						<input type="password" name="senha" class="form-control mt-3" placeholder="Senha"> 
						<div class="mt-3 d-grid gap-2">
							<button class="btn btn-primary">
								Logar
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>