
<section class="mt-5">
	<div class="container">
		<div class="row">
			<div class="col-6">
				<div class="card">
					<div class="card-header">
						<h5 class="card-title">Temperos mais vendidos</h5>
					</div>
					<div class="card-body">
						<table class="table">
						  <thead>
						    <tr>
						      <th scope="col">#</th>
						      <th scope="col">Nome</th>
						      <th scope="col">Undiades</th>

						      
						    </tr>
						  </thead>
						  <tbody>

						  <?php 
						  	
						  // Futura da tabelas vendas
						  	foreach ($this->view->tempero as $tempero) {
						  			if($cont < 5){

						  	?>
						    <tr>
						      <th scope="row"><?= $cont = $cont+1 ?> </th>
						      <td><?= $tempero['nome_tempero'] ?></td>
						      <td><?= $tempero['quantidade']?> </td>
						      
						    </tr>
						 <?php }
						}?> 
						  </tbody>
						</table>
						<div class="d-flex justify-content-end">
							<div><a href="/dashboard" class="nav-link">
								DashBorad 
								<i class="fa-solid fa-arrow-right"></i>
								</a>
							</div>
						</div>
					</div>
				</div>

			</div>
			<div class="col-6">
				<div class="card">
					<div class="card-header">
						<h5 class="card-title">Vendas por Estabelecimento </h5>
					</div>
					<div class="card-body">
						<table class="table">
						  <thead>
						    <tr>
						      <th scope="col">#</th>
						      <th scope="col">Nome</th>
						      <th scope="col">Endereco</th>

						      
						    </tr>
						  </thead>
						  <tbody>
						  	<?php 
						  
						  	foreach ($this->view->empresa  as $value) {
						  		if($i < 5){
						  	
						  	?>
						    <tr>
						      <th scope="row"><?= $i = $i+1?></th>
						      <td><?= $value['nome_emrpesa']?> </td>
						      <td><?= $value['rua']?> </td>
						      
						    </tr>
						    <?php } 
						}?>
						  </tbody>
						</table>
						<div class="d-flex justify-content-end">
							<a href="/dashboard" class="nav-link">
								Mercados
								<i class="fa-solid fa-arrow-right"></i>
								</a>
							</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="mt-5">
	<div class="container">
		<div class="row">
			<div class="col-6">
				<div class="card">
					<div class="card-header">
						<h5 class="card-title">Funcionarios</h5>
					</div>
					<div class="card-body">
						<table class="table">
						  <thead>
						    <tr>
						      <th scope="col">#</th>
						      <th scope="col">Nome</th>
						      <th scope="col">Cargo</th>

						      
						    </tr>
						  </thead>
						  <tbody>
						  	<?php 
						  	
						  	foreach($this->view->usuario  as  $dados1){
						  		if($id < 5){
						  		?>
						    <tr>
						      <th scope="row"><?= $id = $id+1 ?></th>
						      <td><?= $dados1['nome_usuario'] ?></td>
						      <td><?= $dados1['nome_status']?> </td>
						      
						    </tr>
						   <?php } }?>
						  </tbody>
						</table>
						<div class="d-flex justify-content-end">
							<div><a href="/edit" class="nav-link">
								Funcionaios 
								<i class="fa-solid fa-arrow-right"></i>
								</a>
							</div>
						</div>
					</div>
				</div>

			</div>
			<div class="col-6">
				<div class="card">
					<div class="card-header">
						<h5 class="card-title">Vendas por Funcionarios</h5>
					</div>
					<div class="card-body">
						<table class="table">
						  <thead>
						    <tr>
						      <th scope="col">#</th>
						      <th scope="col">Nome</th>
						      <th scope="col">Qtd vendidas por mês</th>

						      
						    </tr>
						  </thead>
						  <tbody>
						    <tr>
						      <th scope="row">1</th>
						      <td>Marcos</td>
						      <td>800 </td>
						      
						    </tr>
						    <tr>
						      <th scope="row">2</th>
						      <td>Henrrique</td>
						      <td>500 </td>
						      
						    </tr>
						    <tr>
						      <th scope="row">3</th>
						      <td >Soarez</td>
						      <td>400</td>
						    </tr>
						  </tbody>
						</table>
						<!-- <div class="d-flex justify-content-end">
							<a href="/dashboard" class="nav-link">
								Mercados
								<i class="fa-solid fa-arrow-right"></i>
								</a>
							</div> -->
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
