<section style="overflow: hidden;">
	<div class="row" > 		
	<div class="col-6" id="div" onload="graficos()"> 
			<div class="painel">
				<h1>Vendas</h1>
				<div id="grafico" style="width: 500px; height:400px">
					
				</div>
			</div>
			
	</div>	
		<div class="col-6"> 
			<div class="painel">
				<h1>Vendas</h1>
			</div>
			
			
	</div>	
	<div class="col-6"> 
			<div class="painel">
				<h1>Vendas</h1>
			</div>
			
			
	</div>	
		<div class="col-6"> 
			<div class="painel">
				<h1>Vendas</h1>
			</div>
			
			
	</div>	

</div>


	
</section>