
<section class="mt-5">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="card">
					<div class="card-header bg-primary">
						<h5 class=" card-title"> Cadastrado com sucésso <i class="fa-solid fa-check i"></i></h5>


					</div>
					<div class="card-body">

						<p class="card-text">
							Cadastrado com sucésso, caso queria cadastrar mais funcionários <a href="/" >Clique aqui </a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>