<!DOCTYPE html>
<html>
<head>
	<title><?= $this->view->pagina?></title>
	<meta charset=utf-8>
	<meta name=description content="">
	<meta name=viewport content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<script src="https://kit.fontawesome.com/ca05319a1a.js" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="/css/style.css">
<script src="/js/javascript.js"></script>
 <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
 <script type="text/javascript">

 	google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);	
            function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Modalidades', 'Porentagem'],
          ['Computador',  1000],
          ['Notbook',  1170],
          ['Smartphone',  660]
                  ]);

        var options = {
          title: 'Tempo gasto ',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.PieChart(document.getElementById('grafico'));

         chart.draw(data, options);
     }

 </script>
 

 
 

</head>
<body>
	<header>
		<nav class="navbar  bg-primary" >
			<div class="container-fluid">
				<a href="" class="nav-link">
					<h4>Sistema de precços</h4>
				</a>
				<button class="navbar-toggler" data-bs-toggle="offcanvas" data-bs-target="#nav">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="offcanvas offcanvas-end" id="nav" >
					<div class="offcanvas-header">
						<h3 class="offcanvas-title">Salomão Temperos</h3>
					</div>
					<div class="offcanvas-body">
						<ul class="navbar-nav justify-content-end flex-grow">
							<li>
								<a href="/" class="nav-link"> 
									<i class="fa-solid fa-house"></i>
									Home</a>
							</li>
							<li>
								<a href="/cadastrarColaborador" class="nav-link">
									<i class="fa-solid fa-address-card"></i>
								Cadastrar Colaborador
							</a>
							</li>
							<li>
								<a href="/vender" class="nav-link">
								<i class="fa-solid fa-dollar-sign"></i>
								Abrir Vendas
							</a>
							</li>
							<li>
								<a href="/dashboard" class="nav-link">
									<i class="fa-solid fa-arrow-trend-up"></i>
								Dashboard vendas
							</a>
							</li>
							<li>
								<a href="/cadastrarProduto" class="nav-link">
									<i class="fa-brands fa-product-hunt"></i>
								Cadastrar Produtos
							</a>
							</li>
							<li>
								<a href="/cadastrarEmpresa" class="nav-link">
									<i class="fa-solid fa-place-of-worship"></i>
								Cadastrar Mercado
							</a>
							</li>
							<li>
								<a href="/sair" class="nav-link">
									<i class="fa-solid fa-arrow-right-from-arc"></i>
								Sair
							</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</nav>
	</header >
		
	
	<?php 
		$this->content();
	?>
	
<!-- jS -->
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</body>
</html>